#include <stdlib.h>
#include <stdio.h>

#include "ai_data.h"
#include "ai_math.h"

const char* DATA_FILE = "ai_data";

// Generated by DenseLayer Shape(8576) Shape(256) [(MemoryRegion5+0)] (MemoryRegion6+0)
Scalar* const restrict DenseLayer_11_WEIGHTS = (Scalar[2195456]){};
Scalar* const restrict DenseLayer_11_BIASES = (Scalar[256]){};
// Generated by Conv3DLayer Shape(3,7,6,1) Shape(3,5,4,64) [(((MemoryRegion5+0)+8448)+0)] (((MemoryRegion5+0)+0)+0)
Scalar* const restrict Conv3DLayer_5_KERNELS = (Scalar[576]){};
Scalar* const restrict Conv3DLayer_5_BIASES = (Scalar[64]){};
// Generated by Conv3DLayer Shape(3,7,6,1) Shape(3,4,3,128) [(((MemoryRegion5+0)+8448)+0)] (((MemoryRegion5+0)+0)+3840)
Scalar* const restrict Conv3DLayer_6_KERNELS = (Scalar[2048]){};
Scalar* const restrict Conv3DLayer_6_BIASES = (Scalar[128]){};
// Generated by DenseLayer Shape(256) Shape(256) [(MemoryRegion6+0)] (MemoryRegion7+0)
Scalar* const restrict DenseLayer_12_WEIGHTS = (Scalar[65536]){};
Scalar* const restrict DenseLayer_12_BIASES = (Scalar[256]){};
// Generated by DenseLayer Shape(256) Shape(256) [(MemoryRegion7+0)] (MemoryRegion8+0)
Scalar* const restrict DenseLayer_13_WEIGHTS = (Scalar[65536]){};
Scalar* const restrict DenseLayer_13_BIASES = (Scalar[256]){};
// Generated by DenseLayer Shape(256) Shape(128) [(MemoryRegion8+0)] (MemoryRegion9+0)
Scalar* const restrict DenseLayer_14_WEIGHTS = (Scalar[32768]){};
Scalar* const restrict DenseLayer_14_BIASES = (Scalar[128]){};
// Generated by DenseLayer Shape(128) Shape(64) [(MemoryRegion9+0)] (MemoryRegion10+0)
Scalar* const restrict DenseLayer_15_WEIGHTS = (Scalar[8192]){};
Scalar* const restrict DenseLayer_15_BIASES = (Scalar[64]){};
// Generated by DenseLayer Shape(64) Shape(1) [(MemoryRegion10+0)] (MemoryRegion11+0)
Scalar* const restrict DenseLayer_16_WEIGHTS = (Scalar[64]){};
Scalar* const restrict DenseLayer_16_BIASES = (Scalar[1]){};

void init_ai_data(){
    FILE *fp = fopen(DATA_FILE, "rb");
    if (!fp){
        printf("fopen(\"%s\") failed\n", DATA_FILE);
        exit(4);
    }

    if (fread(DenseLayer_11_WEIGHTS, sizeof(Scalar), 2195456, fp) != 2195456){
        puts("fread(DenseLayer_11_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_11_BIASES, sizeof(Scalar), 256, fp) != 256){
        puts("fread(DenseLayer_11_BIASES) failed");
        exit(4);
    }
    if (fread(Conv3DLayer_5_KERNELS, sizeof(Scalar), 576, fp) != 576){
        puts("fread(Conv3DLayer_5_KERNELS) failed");
        exit(4);
    }
    if (fread(Conv3DLayer_5_BIASES, sizeof(Scalar), 64, fp) != 64){
        puts("fread(Conv3DLayer_5_BIASES) failed");
        exit(4);
    }
    if (fread(Conv3DLayer_6_KERNELS, sizeof(Scalar), 2048, fp) != 2048){
        puts("fread(Conv3DLayer_6_KERNELS) failed");
        exit(4);
    }
    if (fread(Conv3DLayer_6_BIASES, sizeof(Scalar), 128, fp) != 128){
        puts("fread(Conv3DLayer_6_BIASES) failed");
        exit(4);
    }
    if (fread(DenseLayer_12_WEIGHTS, sizeof(Scalar), 65536, fp) != 65536){
        puts("fread(DenseLayer_12_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_12_BIASES, sizeof(Scalar), 256, fp) != 256){
        puts("fread(DenseLayer_12_BIASES) failed");
        exit(4);
    }
    if (fread(DenseLayer_13_WEIGHTS, sizeof(Scalar), 65536, fp) != 65536){
        puts("fread(DenseLayer_13_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_13_BIASES, sizeof(Scalar), 256, fp) != 256){
        puts("fread(DenseLayer_13_BIASES) failed");
        exit(4);
    }
    if (fread(DenseLayer_14_WEIGHTS, sizeof(Scalar), 32768, fp) != 32768){
        puts("fread(DenseLayer_14_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_14_BIASES, sizeof(Scalar), 128, fp) != 128){
        puts("fread(DenseLayer_14_BIASES) failed");
        exit(4);
    }
    if (fread(DenseLayer_15_WEIGHTS, sizeof(Scalar), 8192, fp) != 8192){
        puts("fread(DenseLayer_15_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_15_BIASES, sizeof(Scalar), 64, fp) != 64){
        puts("fread(DenseLayer_15_BIASES) failed");
        exit(4);
    }
    if (fread(DenseLayer_16_WEIGHTS, sizeof(Scalar), 64, fp) != 64){
        puts("fread(DenseLayer_16_WEIGHTS) failed");
        exit(4);
    }
    if (fread(DenseLayer_16_BIASES, sizeof(Scalar), 1, fp) != 1){
        puts("fread(DenseLayer_16_BIASES) failed");
        exit(4);
    }

    if (fclose(fp) != 0){
        puts("fclose(fp) failed");
        exit(4);
    }
}