#pragma once
#include "ai_math.h"

// Generated by DenseLayer Shape(8576) Shape(256) [(MemoryRegion5+0)] (MemoryRegion6+0)
extern Scalar* const restrict DenseLayer_11_WEIGHTS;
extern Scalar* const restrict DenseLayer_11_BIASES;
// Generated by Conv3DLayer Shape(3,7,6,1) Shape(3,5,4,64) [(((MemoryRegion5+0)+8448)+0)] (((MemoryRegion5+0)+0)+0)
extern Scalar* const restrict Conv3DLayer_5_KERNELS;
extern Scalar* const restrict Conv3DLayer_5_BIASES;
// Generated by Conv3DLayer Shape(3,7,6,1) Shape(3,4,3,128) [(((MemoryRegion5+0)+8448)+0)] (((MemoryRegion5+0)+0)+3840)
extern Scalar* const restrict Conv3DLayer_6_KERNELS;
extern Scalar* const restrict Conv3DLayer_6_BIASES;
// Generated by DenseLayer Shape(256) Shape(256) [(MemoryRegion6+0)] (MemoryRegion7+0)
extern Scalar* const restrict DenseLayer_12_WEIGHTS;
extern Scalar* const restrict DenseLayer_12_BIASES;
// Generated by DenseLayer Shape(256) Shape(256) [(MemoryRegion7+0)] (MemoryRegion8+0)
extern Scalar* const restrict DenseLayer_13_WEIGHTS;
extern Scalar* const restrict DenseLayer_13_BIASES;
// Generated by DenseLayer Shape(256) Shape(128) [(MemoryRegion8+0)] (MemoryRegion9+0)
extern Scalar* const restrict DenseLayer_14_WEIGHTS;
extern Scalar* const restrict DenseLayer_14_BIASES;
// Generated by DenseLayer Shape(128) Shape(64) [(MemoryRegion9+0)] (MemoryRegion10+0)
extern Scalar* const restrict DenseLayer_15_WEIGHTS;
extern Scalar* const restrict DenseLayer_15_BIASES;
// Generated by DenseLayer Shape(64) Shape(1) [(MemoryRegion10+0)] (MemoryRegion11+0)
extern Scalar* const restrict DenseLayer_16_WEIGHTS;
extern Scalar* const restrict DenseLayer_16_BIASES;

void init_ai_data();